### PR TITLE
Add stair step and clean up JSON and HTML

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
The views don't look very pretty and the images need updating but the JSON and HTML should be complete.

### CODE REVIEW

**Review by DanWebster — CHANGES_REQUESTED** [review]
Odd whitespace at the top of the screen during testing on SE (picture attached)
Screen Shot 2019-03-28 at 6 00 15 PM

**Comment by syoung-smallwisdom** [comment]
@DanWebster 

As mentioned, the views aren't pretty. The goal with this is b/c @nategbrown9 is working on the same stuff on Android so the more I can get the functionality, language, etc in, the better. Also, this way the pull requests stay smaller. :)

**Comment by syoung-smallwisdom** [comment]
@DanWebster , @nategbrown9 
Pushed some additional changes, mostly to the layout and design of the hybrid views that include html but have custom coloring for the header/footer.

**Review by DanWebster — APPROVED** [review]
Looks good!

**Pull request merged**
