### PR TITLE
Remove signing team from all framework targets in Research.xcodeproj

### PR DESCRIPTION
**Pull request by kalperin**

### CODE REVIEW

**Comment by kalperin** [comment]
@syoung-smallwisdom

**Review by syoung-smallwisdom — APPROVED** [review]
dagnabit

**Comment by syoung-smallwisdom** [comment]
@kalperin You guys missed the release versions. Fixed that and I'm shepherding this through version tagging. Sorry about that.

**Comment by kalperin** [comment]
> You guys missed the release versions. 

Not so much *us* guys as *me* guys.  I missed that one all by myself 8- ).  Thanks for fixing it!

**Pull request merged**
