### PR TITLE
Add CRF resting heart rate task

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
Added the resting heart rate. This does not include logic for only measuring heart rate once or the updated heart rate step. Additionally, the images include a purple background.

### CODE REVIEW

**Review by DanWebster — CHANGES_REQUESTED** [review]
- Permission request for camera access should come after screen w/ 'Can we turn on your camera and flash' instead of right before the measurement.
- Sidenote that this was not testable in the simulator b/c of error '"libMobileGestalt MobileGestalt.c:875: MGIsDeviceOneOfType is not supported on this platform."' but don't know if this is particular to my versions of xcode, etc.  This works on my device itself though.

**Comment by syoung-smallwisdom** [comment]
@DanWebster Which simulator were you trying to use? I haven't had any problems but I don't run the tests with all 20x of them.

WRT the permissions, it depends upon which task you are running. If it's the resting heart rate, there *isn't* a step to get permission to use the camera. If it is the training task, adding that check is TBD, but worth documenting. Thanks

**Comment by syoung-smallwisdom** [comment]
@DanWebster 
The error appears to be related to the version of Xcode you are running:
https://stackoverflow.com/questions/50701321/xcode-error-on-simulation-mgisdeviceoneoftype-is-not-supported-on-this-platform/52874178

**Comment by DanWebster** [comment]
Running SE, now with upgraded xcode (Version 10.2 (10E125)) will run in simulator

**Review by DanWebster — APPROVED** [review]

**Pull request merged**
