### PR TITLE
Hide the “what you’ll need” label if no icons to show

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**

### CODE REVIEW

**Review by Erin-Mounts — APPROVED** [review]
looks good

**Review by DanWebster — APPROVED** [review]
This fix was "Jimmy John's-quick".  Thank you!

**Comment by DanWebster** [comment]
@dephillipsmichael tagged for reference

**Comment by dephillipsmichael** [comment]
> @dephillipsmichael tagged for reference

Nice catch and thanks for the fix Shannon 👍

**Pull request merged**
