### PR TITLE
build with fastlane  v2.105.2

### PR DESCRIPTION
**Pull request by zaro0508**
Attempt to fix build by using fastlane v2.105.2 as suggested
in https://github.com/fastlane/fastlane/issues/15307

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
@zaro0508 The build is failing. Could you please take a look? Thanks!

**Comment by zaro0508** [comment]
> @zaro0508 The build is failing. Could you please take a look? Thanks!

it's fails when trying to run tests.  should tests be working?  sorry, i don't know anything about the tests or how to fix them @syoung-smallwisdom

**Comment by syoung-smallwisdom** [comment]
> > @zaro0508 The build is failing. Could you please take a look? Thanks!
> 
> it's fails when trying to run tests. should tests be working? sorry, i don't know anything about the tests or how to fix them @syoung-smallwisdom

@zaro0508 All tests pass when I run then on a local copy of that branch in Xcode. I think this is something else.

**Comment by zaro0508** [comment]
> @zaro0508 All tests pass when I run then on a local copy of that branch in Xcode. I think this is something else.

You are correct, the older version of fastlane doesn't work anymore.  The build is doesn't work due to issue https://sagebionetworks.jira.com/browse/IA-854

**Pull request closed without merging**
